name: Kotlin CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Build on Java ${{ matrix.Java }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        working-directory: ebs
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ebs
          path: "ebs/build/libs/*-all.jar"
