name: Web CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 'current', 'latest' ]
    name: Build on Node ${{ matrix.Node }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.Node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.Node }}

      - name: Install NPM Packages
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: "frontend/build/*"